<?xml version="1.0" encoding="utf-8"?><Database Name="Playground" EntityNamespace="DataAccess.Playground.LinqToSql" ContextNamespace="DataAccess.Playground.LinqToSql" Class="PlaygroundContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\ProjectsV13;Initial Catalog=Playground;Integrated Security=True;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="DataAccess.Playground.Properties.Settings" SettingsPropertyName="PlaygroundConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ContactType" Member="ContactTypes">
    <Type Name="ContactType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Usr" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="ContactType_Email" Member="Emails" ThisKey="Id" OtherKey="ContactTypeId" Type="Email" />
      <Association Name="ContactType_Phone" Member="Phones" ThisKey="Id" OtherKey="ContactTypeId" Type="Phone" />
    </Type>
  </Table>
  <Table Name="dbo.EventType" Member="EventTypes">
    <Type Name="EventType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Usr" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="EventType_Event" Member="Events" ThisKey="Id" OtherKey="EventTypeId" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.JerseySize" Member="JerseySizes">
    <Type Name="JerseySize">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Usr" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="JerseySize_Player" Member="Players" ThisKey="Id" OtherKey="JerseySizeId" Type="Player" />
    </Type>
  </Table>
  <Table Name="dbo.Position" Member="Positions">
    <Type Name="Position">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Usr" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="Position_Player" Member="Players" ThisKey="Id" OtherKey="PositionId" Type="Player" />
    </Type>
  </Table>
  <Table Name="roster.Email" Member="Emails">
    <Type Name="Email">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContactTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="ContactType_Email" Member="ContactType" ThisKey="ContactTypeId" OtherKey="Id" Type="ContactType" IsForeignKey="true" />
      <Association Name="Player_Email" Member="Player" ThisKey="PlayerId" OtherKey="Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="roster.Images" Member="Images">
    <Type Name="Image">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Association Name="Player_Image" Member="Player" ThisKey="PlayerId" OtherKey="Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="roster.Phone" Member="Phones">
    <Type Name="Phone">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContactTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Association Name="ContactType_Phone" Member="ContactType" ThisKey="ContactTypeId" OtherKey="Id" Type="ContactType" IsForeignKey="true" />
      <Association Name="Player_Phone" Member="Player" ThisKey="PlayerId" OtherKey="Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="calendar.Event" Member="Events">
    <Type Name="Event">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Opponent" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsHome" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="EventType_Event" Member="EventType" ThisKey="EventTypeId" OtherKey="Id" Type="EventType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="roster.Player" Member="Players">
    <Type Name="Player">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SlackId" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PracticeNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JerseySizeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JerseyPaid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Handedness" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PositionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Skype" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="Player_Email" Member="Emails" ThisKey="Id" OtherKey="PlayerId" Type="Email" />
      <Association Name="Player_Image" Member="Images" ThisKey="Id" OtherKey="PlayerId" Type="Image" />
      <Association Name="Player_Phone" Member="Phones" ThisKey="Id" OtherKey="PlayerId" Type="Phone" />
      <Association Name="JerseySize_Player" Member="JerseySize" ThisKey="JerseySizeId" OtherKey="Id" Type="JerseySize" IsForeignKey="true" />
      <Association Name="Position_Player" Member="Position" ThisKey="PositionId" OtherKey="Id" Type="Position" IsForeignKey="true" />
    </Type>
  </Table>
</Database>